name: Deploy the backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wubble-backend:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/wubble-backend:latest